
version: '3.8'

services:
  postgres-db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgAdmin:
    depends_on:
      - postgres-db
    image: dpage/pgadmin4:7.6
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}


