export enum PastorSearchType {
  FirstNames = 'first_names',
  LastNames = 'last_names',
  FullNames = 'full_names',
  OriginCountry = 'origin_country',
  BirthDate = 'birth_date',
  BirthMonth = 'birth_month',
  Gender = 'gender',
  MaritalStatus = 'marital_status',
  ResidenceCountry = 'residence_country',
  ResidenceDepartment = 'residence_department',
  ResidenceProvince = 'residence+province',
  ResidenceDistrict = 'residence_district',
  ResidenceUrbanSector = 'residence_urban_sector',
  ResidenceAddress = 'residence_address',
  RecordStatus = 'record_status',
}

export const PastorSearchTypeNames: Record<PastorSearchType, string> = {
  [PastorSearchType.FirstNames]: 'Nombres',
  [PastorSearchType.LastNames]: 'Apellidos',
  [PastorSearchType.FullNames]: 'Nombres y Apellidos',
  [PastorSearchType.BirthDate]: 'Fecha de nacimiento',
  [PastorSearchType.BirthMonth]: 'Mes de nacimiento',
  [PastorSearchType.Gender]: 'Género',
  [PastorSearchType.MaritalStatus]: 'Estado civil',
  [PastorSearchType.OriginCountry]: 'País (origen)',
  [PastorSearchType.ResidenceCountry]: 'País (residencia)',
  [PastorSearchType.ResidenceDepartment]: 'Departamento (residencia)',
  [PastorSearchType.ResidenceProvince]: 'Provincia (residencia)',
  [PastorSearchType.ResidenceDistrict]: 'Distrito (residencia)',
  [PastorSearchType.ResidenceUrbanSector]: 'Sector Urbano (residencia)',
  [PastorSearchType.ResidenceAddress]: 'Dirección (residencia)',
  [PastorSearchType.RecordStatus]: 'Estado de registro',
};
